# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7f5224740863056115c2ded227c29bb1b4ebe8dbd0263f9cc8486520d7c504d12a00da4d355b157090a15967371ef1959e431add4653005bc52421da53a4600

test:
  secret_key_base: a30ad3b2c1347c964380858bc4cf567189db3d45be8cda95151c876bc0da1ff9b939c49d0cbbc0cec95ffeeb5a0bc4261be36e18f91612bffaed1ba17f249297

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
